services:
  web:
    build:
      target: development
    volumes:
      - ./apps/web:/app/apps/web:cache
      - web-node-modules:/app/apps/web/node_modules
    environment:
      - NODE_ENV=development

  admin:
    build:
      target: development
    volumes:
      - ./apps/admin:/app/apps/admin:cache
      - admin-node-modules:/app/apps/admin/node_modules
    environment:
      - NODE_ENV=development

volumes:
  web-node-modules:
  admin-node-modules:
